### ISSUE TITLE
Deploying / Using with Carton

### ISSUE THREAD

**Issue by slobo** [Perl5-Alien/Alien-Base#122]
This may be completely out of the scope, but I'm looking for a solution to deploy perl apps on naive servers. Currently ``Carton`` works great to package up all CPAN dependencies on the build machine and then transfer the entire ``local/`` onto the server with the same base OS and have it all run without issues. (I don't do ``carton bundle`` as then everything would need to be recompiled on the target) 
However, this method depends on target having the same shared libraries as the build system. Eg, ``DBD::Pg`` needs to have postgres client libraries installed on both build and target machines. Would ``Alien::Base`` be able to help with this and somehow include the shared libraries in the ``local/`` so that the only requirement of the target system is to have the same base OS as the build machine?
Thanks

**Comment by plicease** [comment]
If the module uses `Alien::Base` based module to locate the library, then yes.  In your example, if `DBD::Pg` used (theoretical) `Alien::libpq` to discover or build the PostgreSQL library, then it could be bundled in a `local/` directory.  `Alien::Base` will use the system library by default, but this can easily be changed by setting the environment variable `ALIEN_FORCE=1` when you install `Alien::libpq`.  Unfortunately only a few modules on CPAN take advantage of Alien tech at the moment so short term this is probably not very helpful for you.

Now that `Alien::Base` is more reliable, I have been thinking of prodding some module authors to convert to Alien (`Alien::LibXML` and `Alien::LibYAML` would be great if more widely used, for example).  Where Alien modules are available I think they are now more reliable than `Devel::CheckLib`.  One thing that might help here would be some `Devel::CheckLib` integration.  If CPAN developers are too conservative to migrate to Alien, perhaps using it optionally if installed would be a place to start.

**Comment by mohawk2** [comment]
@plicease I think an effort to achieve integration between A::B and D::C is a great idea both for user convenience, and for simple reasons of alphabetical beauty. Reminds me of the recent-ish effort to integrate between Inline and ExtUtils::Depends.

**Comment by slobo** [comment]
@plicease Thanks for the insights, makes sense.
