### ISSUE TITLE
Create a Alien::Base::ModuleBuild::Repository::Git to handle downloading source from Git repos

### ISSUE THREAD

**Issue by zmughal** [Perl5-Alien/Alien-Base#124]
Some projects only release their code via Git and it might be useful to have a way to specify a Git repo along with a Git commit SHA or a version tag.

**Comment by plicease** [comment]
I had this in the back of my mind for a while now too.  We can use something like `Git::Wrapper` to fetch git based projects, but it isn't reliable enough to make a hard prereq for `Alien::Base`.  It could be injected as a prereq for projects that require it only, or we could write a stand alone `Alien-Base-ModuleBuild-Repository-Git`.  The issue I see here is that the API for Alien::Base::ModuleBuild::Repository is not documented, and arguably could use some love.  I would like to see the repository fetch be more pluggable in general.

**Comment by jberger** [comment]
On Tue, May 26, 2015 at 7:21 AM Graham Ollis <notifications@github.com>
wrote:

> I had this in the back of my mind for a while now too. We can use
> something like Git::Wrapper to fetch git based projects, but it isn't
> reliable enough to make a hard prereq for Alien::Base. It could be
> injected as a prereq for projects that require it only, or we could write a
> stand alone Alien-Base-ModuleBuild-Repository-Git.
>
 It does seem useful, though I would encourage sticking to releases (tags)
rather than pulling master.

> The issue I see here is that the API for
> Alien::Base::ModuleBuild::Repository is not documented, and arguably could
> use some love. I would like to see the repository fetch be more pluggable
> in general.
>
Yes, indeed. I had grand architecture plans for that whole system.
Pluggable mechanisms for selecting versions etc. Remember that one of my
design goals was not to have to release a new version of the CPAN module
when the upstream library got a (compatible) update.

**Comment by plicease** [comment]
@jberger I am not sure what you are referring to as I did not suggest pulling from master.  I was discussing how to specify git itself as a prerequisite reliably.  I have had good experience with using `Git::Wrapper`, but it barfs in either config or test if you do not have git.  If ::Repository::Git were in a separate dist with a prereq on `Git::Wrapper` then it is less problematic.

**Comment by jberger** [comment]
No, you didn't say anything about that, I was just mentioning it off the
cuff as a reminder. I know that @preaction has had to deal with tests
depending on git state, do you have any thoughts?

**Comment by preaction** [comment]
I usually just add my Git-interaction module as a "recommends" and then:

```
use Test::More;
BEGIN { eval 'use Git::Repository; 1;' or plan skip_all => 'Git::Repository required for this test' };
```

I think it'd be better to have it as a separate dist because the author of the CPAN module using the Git version would need to explicitly depend on either it, or the Git module you use.

**Comment by plicease** [comment]
Does not solve this entirely but I also did want to just mention that github based projects can be downloaded (by tag, branch sha, etc) through the http interface:

**Comment by plicease** [comment]
I wanted to add a note that Joel and I were talking about AB at YAPC::NA this week and I said that I thought the fetch mechanism needed an overhaul and he agreed (or at least agreed that would be okay).  I am going to try and take a stab at it in the next couple of months and will likely use git support as a use case for the plugability aspect.

**Comment by plicease** [comment]
Here is an example of how you could use git as a package source using `dontpanic` under the `Alien-Build` recipe system:

```perl
use alienfile;

probe sub { 'share' };

share {

  download [
    [ "git clone --bare https://github.com/Perl5-Alien/dontpanic.git" ]
  ];

  extract [
    [ "git clone %{alien.install.download}" ]
  ];

  plugin 'Build::Autoconf' => ();

  build [
    'git checkout v1.00',
    'bash autogen.sh',
    '%{configure} --disable-shared --prefix=%{alien.install.prefix}',
    '%{make}',
    '%{make} install',
  ];


};
```

**Comment by mohawk2** [comment]
I'd like as much as possible to use other people's work for this stuff - is it possible to use `cpanm`'s code directly to achieve the build-from-git?

**Comment by plicease** [comment]
@mohawk2 Not sure, I suspect that it is that it is perl/cpan specific, but if someone can point me to an API we can evaluate it.  The point here is less "hey look I can use Alien::Build to download from git" and more "hey look I can use Alien::Build to download as long as there is a command to do it."  `Alien::Build` has a negotiation mechanism for picking the best tools for the actual downloading from common protocols, like http, ftp, local file, but for stuff that hasn't been added to the core yet, (like git atm) being able to provide a command that does the trick is very powerful.

**Comment by zmughal** [comment]
An example of this that I had in mind was [CastXML](https://github.com/CastXML/CastXML). It has no release tags.

**Comment by plicease** [comment]
This example works with CastXML for the download, although the build fails.

I am going to release Alien-Build-Git probably later today or tomorrow.  I consider this issue addressed.
