### ISSUE TITLE
FAQ (or feature) for using foo-config instead of pkg-config

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-Base#136]
Some packages come with a foo-config but no pkg-config .pc file.  I think that pkg-config should still be used when available because it uses a standard interface when it is supported by the package (and we have a pure perl implementation for when a real pkg-config is not available).  However, it would be good to have a way of saying "use foo-config as pkg-config for cflags and libs".  We already have a hook for saying "use foo-config --version to determine the system version".

This was my work around for an existing Alien dist, but I am not certain I have it quite right yet:

https://github.com/plicease/Alien-qd/commit/85069bb2ad054f84b90d02160ad817fc4a509ae2

Alternatively, when I was writing the FAQ I tried to find a common example where the package provided a foo-config but no pkg-config .pc file.  I couldn't find one, so perhaps it isn't a common problem.  Maybe a refinement on the Alien::qd example and an addition to the FAQ would be sufficient.

**Comment by zmughal** [comment]
I don't think it is common. All I see on my system are libgeos (`geos-config`) and wxWidgets (`wx-config`).

**Comment by plicease** [comment]
I have a bunch:

```
twin% ls /usr/bin/*-config
/usr/bin/apt-config*        /usr/bin/kbd-config*        /usr/bin/libpng12-config*   /usr/bin/nspr-config*       /usr/bin/rarian-sk-config*
/usr/bin/curl-config*       /usr/bin/kde4-config*       /usr/bin/libusb-config*     /usr/bin/pcre-config*       /usr/bin/scrollkeeper-config@
/usr/bin/freetype-config*   /usr/bin/krb5-config*       /usr/bin/ncurses5-config*   /usr/bin/pkg-config*        /usr/bin/xdelta-config*
/usr/bin/gpg-error-config*  /usr/bin/libgcrypt-config*  /usr/bin/ncursesw5-config*  /usr/bin/python2.7-config*  /usr/bin/xfce4-notifyd-config*
/usr/bin/guile-config*      /usr/bin/libpng-config@     /usr/bin/net-snmp-config*   /usr/bin/qd-config*         /usr/bin/xml2-config*
```

most of these also have .pc files though.  A pointer to an example (like Alien::qd) would probably be a helpful trail of bred crumbs for those who run into it.

**Comment by plicease** [comment]
Trivial with `Alien::Build`.
