### ISSUE TITLE
Discovery of non- pkg-config system packages

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-Base#137]
This seems to be a common enough pattern that it ought to be implemented in `Alien::Base`

https://github.com/plicease/Alien-Chipmunk/blob/27272c2474d905cfe88545e82f93b4728d16d550/inc/My/ModuleBuild.pm

I think the only parameter here would be the C source code that prints out the version (usually it can get this either from the .h file or from a library function, or as in this case from a static varaible), since we have the cflags and libs from the alien_provides_ parameters.

I plan on turning this into a PR some time in the future, unless someone beats me to it.

**Comment by mohawk2** [comment]
Embrace all the things!

**Comment by plicease** [comment]
Another example of this is here 
https://github.com/run4flat/Alien-FFCall/pull/2

**Comment by plicease** [comment]
This is (in my opinion) easier to address using the `Alien-Build` recipe system.  For example bzip2:

```perl
use alienfile;
use Config;
use Path::Tiny qw( path );

plugin 'Probe::CBuilder' => (
  libs    => '-lbz2',
  version => qr/version = '(.*?)[,']/,
  program => q{
#include <stdio.h>
#include <bzlib.h>

int main(int argc, char *argv[])
{
  printf("version = '%s'\n", BZ2_bzlibVersion());
  return 0;
}
},
);
...
```

a complete commented example is here:

https://github.com/plicease/Alien-Build/blob/master/example/bzip2.alienfile

**Comment by plicease** [comment]
Handled quite well with `Alien::Build`.
