### ISSUE TITLE
Download of JTPALMER/Alien-Chipmunk-0.001000.tar.gz broken with 0.025

### ISSUE THREAD

**Issue by eserte** [Perl5-Alien/Alien-Base#150]
See subject. If I use Alien-Base-0.024, then the download works again. I see some URI-related change in the CHANGES file --- maybe this is causing the problem?

@jtpalmer : FYI (because of the UNKNOWN reports which will appear @ cpantesters now).

**Comment by plicease** [comment]
I am looking into this.  I have a good idea of what is going on here.

**Comment by plicease** [comment]
@jtpalmer for a work around you can change location in the repository section to include the trailing /
