### ISSUE TITLE
Fix AppVeyor Config

### ISSUE THREAD

**Issue by wbraswell** [Perl5-Alien/Alien-Base#174]
AppVeyor looks like it's using an old version of Perl and crashing before it can start actually running tests:

https://ci.appveyor.com/project/plicease/alien-base/build/1.0.136

Please see the link below for a working AppVeyor config file, used by Alien::astyle:

https://github.com/wbraswell/alien-astyle/blob/master/appveyor.yml

**Comment by plicease** [comment]
Thank you for the pointers.

**Comment by wbraswell** [comment]
:+1:
