### ISSUE TITLE
alien_helper does not work as expected

### ISSUE THREAD

**Issue by MaxPerl** [Perl5-Alien/Alien-Base#182]
I tried alien_helpers, but They didn't work as expected. I think the problem is that the code is executed twice. Here a little code snippet (I just want to change the dir before building becaus the source archive has several subdirectories for different OSes):

```
use Alien::Base::ModuleBuild;
# See perldoc Module::Build for details of how this works

my $builder = Alien::Base::ModuleBuild->new
    ( module_name     => 'Alien::Tcl',
      license         => 'perl',
      alien_repository => {
      			protocol => 'local',
      			location => 'src',
      			exact_filename => 'tcl866-src.zip',				
      },
      alien_helper => {
      	'chdir' => 'chdir "$CWD/win"'
      },
      alien_build_commands => ['%{chdir}', '%c --prefix=%s --enable-64bit', 'make'],
    )->create_build_script;
```

The error message is as follow:

> 
>  + 1
> Can't exec "1": No such file or directory at /usr/share/perl5/Module/Build/Base.pm line 5538.
> External command (1) failed! Error: -1
>  at ./Build line 60.
> Failed
> Build not completed at ./Build line 60.

By the way: If I pass a code ref `alien_helper => sub {...}` I get the following error as early as I execute perl Build.PL:

> Encountered CODE ref, using dummy placeholder at /usr/lib/x86_64-linux-gnu/perl/5.22/Data/Dumper.pm line 231.

**Comment by MaxPerl** [comment]
Dear plicease,
Thank you very much for your help.
I got it with following command:
`alien_build_commands => [ 'cd win; %c --prefix=%s --enable-64bit', 'make -C win' ],`

Nevertheless I am a little bit confused. Because the following don't work. And I don't know why:
`alien_build_Commands => [ 'cd win; %c --prefix=%s --enable-64bit', 'make -C win' ],`
With this the cd part is simply bypassed.
and with 
`alien_build_commands => [ 'cd win', '%c --prefix=%s --enable-64bit', 'make -C win' ],`
I get the error, that the command cd was not found.

Has anyone an idea why the first works and the others don't?

Anyway thank you very much for your help...

**Comment by plicease** [comment]
The second  was my bad, I believe I accidentally capitalized `Commands`  which is wrong!

I wouldn't expect the third version to work, but I am puzzled by the error that you got.

**Comment by MaxPerl** [comment]
Okay next problem. I test it no on windows (before I worked on Linux). On Windows I get the error that the filename, the directory name or the volume label syntax is incorrect.

**Comment by plicease** [comment]
Try `"cd win && %c --prefix=%s --enable-64bit"`  that should work in both windows and linux.

**Comment by MaxPerl** [comment]
Thanks for your help. Now cd win is executed before ./configure. Unfortunately the Build script now stopped after configure. With ["cd win && %c --prefix=%s --enable-64bit && make"] it stopped after the make process and the script doesn't enter in the installation stage.

**Comment by plicease** [comment]
If you have the Alien dist you are working on somewhere public that I can see (preferably GitHub) I may be able to help.  Also useful if there are any diagnostics emitted from either `make` or perl or `AB::MB`.

**Comment by MaxPerl** [comment]
Hi Plicease,
Thanks for your help. [Herel](https://github.com/MaxPerl/Alien-Tcl) you can find the repo. It is in a very early stadium. It concerns [the following bug report](https://rt.cpan.org/Public/Bug/Display.html?id=71535). My target was to develop the same for Tk and so on. But at the moment I think that this is perhaps over my abilities...

**Comment by plicease** [comment]
Thank you for the detail.  I am adding myself as a CC: on the RT issue in case I can help there.  It doesn't look like a bug in AB atm, so I am going to close this one.

**Comment by plicease** [comment]
btw- I will take a look at this when I get home and have my PC to test on but that won't be for two weeks at least.
