### ISSUE TITLE
[PRC] April assignment: how may I be of help?

### ISSUE THREAD

**Issue by JJ** [Perl5-Alien/Alien-Base#185]
I got this assigned during April. I see there are some unresolved issues. Should I start there or is there anything else you'd like me to do?

**Comment by plicease** [comment]
Hi JJ,  welcome!

I don't actually think any of the currently open issues are appropriate to be honest :/  They are either low priority (#164), in progress (#156) or have more to do with other projects than this one (#124, #123).

One thing that we really do need is better documentation.  I have been aware of this for a while, and have been working on it when I can, but of course I write it from an insiders perspective.

One big change that we have made recently is to split Alien::Build::ModuleBuild (ABMB) into a separate distribution with the intent of emphasizing Alien::Build + alienfile (also in a separate dist for now) instead, but much of the documentation still refers to ABMB.  Any references in Alien-Base should preferrably refer to Alien::Build + alienfile first and optionally reference ABMB.  If you had the time, a great way to do this would be to actually try to implement an alien using Alien::Base + alienfile using the current documentation.  That would definitely give you a good insight into where the documentation is weak.  If you don't have that kind of time, I am sure just reading the documentation you could find some iffy stuff that needs fixing.  I am happy to explain how anything does or is supposed to work.

**Comment by JJ** [comment]
2017-04-01 16:04 GMT+02:00 Graham Ollis <notifications@github.com>:

> Hi JJ, welcome!
>
Thanks!


> One thing that we really do need is better documentation. I have been
> aware of this for a while, and have been working on it when I can, but of
> course I write it from an insiders perspective.
>
> One big change that we have made recently is to split
> Alien::Build::ModuleBuild (ABMB) into a separate distribution with the
> intent of emphasizing Alien::Build + alienfile (also in a separate dist for
> now) instead, but much of the documentation still refers to ABMB. Any
> references in Alien-Base should preferrably refer to Alien::Build +
> alienfile first and optionally reference ABMB. If you had the time, a great
> way to do this would be to actually try to implement an alien using
> Alien::Base + alienfile using the current documentation. That would
> definitely give you a good insight into where the documentation is weak. If
> you don't have that kind of time, I am sure just reading the documentation
> you could find some iffy stuff that needs fixing. I am happy to explain how
> anything does or is supposed to work.
>
> OK, I'll take a look at that and see if I feel capable of doing it. Thanks
for answering!
