### ISSUE TITLE
Cross-platform packaging system?

### ISSUE THREAD

**Issue by mohawk2** [Perl5-Alien/Alien-Base#45]
The idiomatic way forward on Unix-alikes is to go with PkgConfig. Is there already a perl-ish way of dealilng with this cross-platform?

**Comment by plicease** [comment]
Opened a ticket for registry detection as #153.   Interested parties can open tickets for default install location probe.  Specific package examples for such a ticket would greatly increase the likelihood that it would actually get implemented.

It is my opinion that there aren't really any good cross platform ways to detect packages.  The approach that we have made, in practice is to add detection methods as they can be abstracted out of specific `Alien::` implementations into `Alien::Base`.  Sine this is an open ended issue, I am going to close it.
